{"files":[{"patch":"@@ -40,1 +40,1 @@\n-    void testContextClassLoaderIsSetAndRestored() throws InterruptedException {\n+    void testContextClassLoaderIsSetAndRestored() throws Exception {\n@@ -53,20 +53,1 @@\n-\n-        try {\n-            future.get();\n-        } catch (Exception e) {\n-            \/\/ If the task threw an exception, unwrap it\n-            if (e instanceof java.util.concurrent.ExecutionException) {\n-                \/\/ Unwrap the ExecutionException to get the underlying cause\n-                Throwable cause = e.getCause();\n-                if (cause instanceof AssertionError) {\n-                    \/\/ If the cause is an AssertionError, rethrow the error\n-                    throw (AssertionError) cause;\n-                } else {\n-                    \/\/ Rethrow other exceptions as RuntimeException\n-                    throw new RuntimeException(\"Unexpected exception during test execution\", cause);\n-                }\n-            } else {\n-                \/\/ Rethrow if the exception isn't wrapped in ExecutionException\n-                throw new RuntimeException(\"Unexpected exception\", e);\n-            }\n-        }\n+        future.get();\n","filename":"test\/jdk\/java\/util\/concurrent\/forkjoin\/ContextClassLoaderTest.java","additions":2,"deletions":21,"binary":false,"changes":23,"status":"modified"}]}