[{"commit":{"message":"nit change"},"files":[{"filename":"test\/jdk\/jdk\/classfile\/VerifierSelfTest.java"}],"sha":"af796a0df3c0d18762776b12d262915ea736fee1"},{"commit":{"message":"wrapped ClassFile::verify(Method) + added test"},"files":[{"filename":"src\/java.base\/share\/classes\/jdk\/internal\/classfile\/impl\/ClassFileImpl.java"},{"filename":"test\/jdk\/jdk\/classfile\/VerifierSelfTest.java"}],"sha":"c5f6e0187a3ee6091417aaaec2014c6de411942f"},{"commit":{"message":"8333812: ClassFile.verify() can throw exceptions instead of returning VerifyErrors"},"files":[{"filename":"src\/java.base\/share\/classes\/jdk\/internal\/classfile\/impl\/BoundAttribute.java"},{"filename":"src\/java.base\/share\/classes\/jdk\/internal\/classfile\/impl\/verifier\/VerifierImpl.java"},{"filename":"test\/jdk\/jdk\/classfile\/VerifierSelfTest.java"}],"sha":"32476edfd521533582e27cb6eb809837e9b91b22"}]